/**
 * 题库：module 分为 interview（面试印象/表达）与 skills（工作必会）
 * level 1-33 与 UI 段位对应；type: choice | fill | match | multi
 * multi：options 为选项数组；correctIndexes 为正确项下标（从 0 开始，需升序唯一）
 */
window.AI_TRAINER_QUESTIONS = [
  // ---------- 面试 · 入门 1-11 ----------
  {
    id: "iv-001",
    module: "interview",
    level: 1,
    type: "choice",
    question: "老师说的 AI 行业本质竞争，正在从「单纯比模型」转向什么？",
    options: ["只比谁广告多", "数据质量 + 底层算力", "只比公司人数", "只比 App 下载量"],
    answerIndex: 1,
    explanation: "笔记：模型能力趋同后，胜负手在数据质量与算力（硬件）。",
  },
  {
    id: "iv-002",
    module: "interview",
    level: 2,
    type: "choice",
    question: "「具身智能」大致指什么方向？",
    options: ["只做聊天机器人", "AI 进入实体设备与物理世界（机器人、汽车等）", "只做网页插件", "只做表格统计"],
    answerIndex: 1,
    explanation: "AI+硬件、机器人、车机等，把智能从屏幕延伸到实体。",
  },
  {
    id: "iv-003",
    module: "interview",
    level: 3,
    type: "fill",
    question: "国产算力与芯片被卡脖子背景下，笔记提到国内要发展自己的芯片，例如华为____、寒武纪等。（填简称即可）",
    answers: ["昇腾", "升腾"],
    explanation: "华为昇腾等代表国产算力路线。",
  },
  {
    id: "iv-004",
    module: "interview",
    level: 4,
    type: "choice",
    question: "笔记中的「AI 六小龙」主要指哪类公司？",
    options: ["只做外卖平台", "2023 前后崛起的一批大模型创业公司", "只做传统数据库", "只做游戏代练"],
    answerIndex: 1,
    explanation: "智谱、MiniMax、百川、零一万物、阶跃星辰、月之暗面等（行业说法会演变）。",
  },
  {
    id: "iv-005",
    module: "interview",
    level: 5,
    type: "match",
    question: "把「公司」与「特点」连起来（依次点左边再点右边配对）",
    pairs: [
      ["DeepSeek", "工种多工程师，训练数据常外包"],
      ["字节 DMC", "为 Seed 等提供高质量数据"],
      ["中小创业公司", "学习曲线陡、扁平、可能 API 慷慨"],
    ],
    explanation: "大厂分工细；DeepSeek 特点来自笔记；创业公司成长快。",
  },
  {
    id: "iv-006",
    module: "interview",
    level: 6,
    type: "choice",
    question: "「涌现 Emergence」在课堂语境里最接近的意思是？",
    options: ["模型一定会变小", "规模堆到一定程度后突然出现新能力", "数据越多越慢", "显卡一定会坏"],
    answerIndex: 1,
    explanation: "数据/算力/算法堆叠到临界点，能力跃迁式出现（如高阶推理）。",
  },
  {
    id: "iv-007",
    module: "interview",
    level: 7,
    type: "choice",
    question: "「幻觉」主要原因不包括下列哪一项？",
    options: ["训练数据有错", "领域数据缺失", "模型逐词预测一旦走错可能一路编下去", "用户电脑内存太小"],
    answerIndex: 3,
    explanation: "幻觉与数据错误、缺失、概率生成链式错误相关；与用户内存无直接关系。",
  },
  {
    id: "iv-008",
    module: "interview",
    level: 8,
    type: "fill",
    question: "面试里描述项目难点与解决思路，常用____法则讲清楚背景-任务-行动-结果。（四个字母大写）",
    answers: ["STAR"],
    explanation: "笔记第二周写法为 STAR（老师口误记成 S4T AR），简历与面试通用。",
  },
  {
    id: "iv-009",
    module: "interview",
    level: 9,
    type: "choice",
    question: "COT（思维链）与「只改提示词」的关系，哪句最准确？",
    options: ["COT 一定会改变模型全部参数", "Zero-shot COT 可以只用一句「让我们一步步思考」而不训模型", "COT 只能用于图片", "COT 是数据库协议"],
    answerIndex: 1,
    explanation: "提示词层面即可触发分步推理；SFT/RLHF 是更强但成本更高的路径。",
  },
  {
    id: "iv-010",
    module: "interview",
    level: 10,
    type: "choice",
    question: "Agent 与「只会聊天的 LLM」核心差异是？",
    options: ["Agent 不能联网", "Agent 强调规划、记忆、工具调用等解决任务", "LLM 一定更大", "没有差异"],
    answerIndex: 1,
    explanation: "从「回答问题」走向「解决问题」：规划、记忆、工具调用。",
  },
  {
    id: "iv-011",
    module: "interview",
    level: 11,
    type: "choice",
    question: "RAG 主要解决哪类问题？",
    options: ["显卡驱动", "给模型外挂知识库，补「不知道/过时」", "压缩视频文件", "键盘打字速度"],
    answerIndex: 1,
    explanation: "Retrieval-Augmented Generation：检索增强生成，补专业与时效。",
  },

  // ---------- 面试 · 中阶 12-22 ----------
  {
    id: "iv-012",
    module: "interview",
    level: 12,
    type: "choice",
    question: "笔记里「模型训练三要素」不包括？",
    options: ["算力 GPU", "算法架构（如 Transformer）", "数据", "办公室绿植数量"],
    answerIndex: 3,
    explanation: "算力+算法+数据；金句：吃什么就拉什么。",
  },
  {
    id: "iv-013",
    module: "interview",
    level: 13,
    type: "fill",
    question: "大模型生成文字时，本质是预测下一个____的概率分布，而不是查字典式检索。",
    answers: ["词", "token", "Token", "词元"],
    explanation: "概率生成机制；英文常称 token。",
  },
  {
    id: "iv-014",
    module: "interview",
    level: 14,
    type: "match",
    question: "把「后训练阶段」与「作用」配对",
    pairs: [
      ["SFT", "用标准答案教模型「怎么做对」"],
      ["RLHF", "用人类排序教模型「怎样更好」"],
      ["预训练", "海量无监督自学语言规律"],
    ],
    explanation: "预训练→base；后训练 SFT 再 RLHF 对齐人类偏好。",
  },
  {
    id: "iv-015",
    module: "interview",
    level: 15,
    type: "choice",
    question: "为什么笔记说「base model 像个读很多书但不会打交道的呆子」？",
    options: ["因为它不能运行", "它主要学了语言统计，未充分学对话与助手行为", "它一定比 GPT 小", "它不能算数"],
    answerIndex: 1,
    explanation: "预训练后还要 SFT/RLHF 等教会对话与对齐。",
  },
  {
    id: "iv-016",
    module: "interview",
    level: 16,
    type: "choice",
    question: "面试谈「行业动态」时，下列哪个表述更贴近笔记精神？",
    options: ["只背一个模型名字即可", "能说出趋势：数据/算力、具身智能、国产芯片等", "只说我会用 Excel", "模型之间永远没有差异"],
    answerIndex: 1,
    explanation: "展示结构化认知：趋势、岗位、公司分工。",
  },
  {
    id: "iv-017",
    module: "interview",
    level: 17,
    type: "choice",
    question: "ReAct 框架里的三个循环要素是？",
    options: ["复制、粘贴、保存", "Thought（思考）、Action（行动）、Observation（观察）", "CPU、内存、硬盘", "需求、开发、测试"],
    answerIndex: 1,
    explanation: "Reasoning + Acting：思考→行动→观察→再思考。",
  },
  {
    id: "iv-018",
    module: "interview",
    level: 18,
    type: "fill",
    question: "RLHF 英文全称里，H 代表 ____ Feedback。（单词）",
    answers: ["Human", "human"],
    explanation: "Reinforcement Learning from Human Feedback。",
  },
  {
    id: "iv-019",
    module: "interview",
    level: 19,
    type: "choice",
    question: "「过拟合」最贴切的比喻是？",
    options: ["没学过", "死记硬背训练集、换题就懵", "数据太多", "显卡过热"],
    answerIndex: 1,
    explanation: "学得太死；欠拟合是学得不够。",
  },
  {
    id: "iv-020",
    module: "interview",
    level: 20,
    type: "choice",
    question: "笔记里对「上下文工程师 CE」的关键认知是？",
    options: ["上下文越多越好", "输入越多结果越烂，要精简相关上下文", "CE 不管 prompt", "CE 只写 SQL"],
    answerIndex: 1,
    explanation: "管理上下文+瘦身；与「模型分心」相关。",
  },
  {
    id: "iv-021",
    module: "interview",
    level: 21,
    type: "choice",
    question: "MCP（Model Context Protocol）主要解决什么？",
    options: ["统一应用接口，让 AI 工具能调用外部软件", "修电脑主板", "压缩图片", "发快递"],
    answerIndex: 0,
    explanation: "模型上下文协议：连接 Cursor 等与 Chrome、飞书等工具。",
  },
  {
    id: "iv-022",
    module: "interview",
    level: 22,
    type: "match",
    question: "术语与含义配对",
    pairs: [
      ["Embedding", "文本变成向量，语义相近则向量相近"],
      ["Top K", "检索返回最相似的前 K 个 chunk"],
      ["Token", "计费与处理的最小文本单位"],
    ],
    explanation: "RAG 流程里 embedding、向量库、Top K 是高频词。",
  },

  // ---------- 面试 · 高阶 23-33 ----------
  {
    id: "iv-023",
    module: "interview",
    level: 23,
    type: "choice",
    question: "RAG 能很好缓解「幻觉」中的哪一类？",
    options: ["数据缺失导致不知道", "训练数据本身错误", "概率链选词错误", "键盘坏了"],
    answerIndex: 0,
    explanation: "外挂知识补「不知道」；数据错误与概率错并不万能解决。",
  },
  {
    id: "iv-024",
    module: "interview",
    level: 24,
    type: "choice",
    question: "为什么 Top K 不能盲目设得很大？",
    options: ["因为 K 越大越快", "召回太多 chunk 会稀释注意力，生成反而变差", "K 与法律有关", "没有影响"],
    answerIndex: 1,
    explanation: "与「输入越多生成越烂」一致，要权衡召回与噪声。",
  },
  {
    id: "iv-025",
    module: "interview",
    level: 25,
    type: "fill",
    question: "多轮对话标注里，后续回答若约____% 大量抄第一轮，算「重复摘抄」问题。（填数字）",
    answers: ["30", "40", "30-40", "30到40", "35"],
    explanation: "笔记：30%-40% 抄第一轮可判问题，模型偷懒。",
  },
  {
    id: "iv-026",
    module: "interview",
    level: 26,
    type: "choice",
    question: "三人一致性原则里，三人排序都不一样时通常？",
    options: ["随便选一个", "继续加标直到一致或开会", "直接丢弃项目", "只用一人"],
    answerIndex: 1,
    explanation: "降低主观性：多数决；不一致则加标或讨论。",
  },
  {
    id: "iv-027",
    module: "interview",
    level: 27,
    type: "choice",
    question: "DeepSeek R1 流程里，训练师主要参与哪类环节（按笔记总结）？",
    options: ["只做预训练爬全网", "冷启动 SFT 与拒绝采样后的 SFT 等阶段", "只负责买显卡", "不参与"],
    answerIndex: 1,
    explanation: "阶段1冷启动 CoT 数据与阶段3等 SFT 相关参与度高。",
  },
  {
    id: "iv-028",
    module: "interview",
    level: 28,
    type: "choice",
    question: "「有效反思」与「无效反思」区分，哪条更像有效？",
    options: ["嗯…可能吧…也许不是…", "指出前面哪步算错并改正推理链", "一直重复同样一句话", "拒绝回答"],
    answerIndex: 1,
    explanation: "COT 标注：能定位错误步骤并纠正是有效反思。",
  },
  {
    id: "iv-029",
    module: "interview",
    level: 29,
    type: "fill",
    question: "笔记中「快思考 / 慢思考」对应：没有思维链时模型偏直觉快答；有 COT 后更接近____思考。（填：慢）",
    answers: ["慢"],
    explanation: "卡尼曼双系统类比：COT 让模型进入分步慢思考。",
  },
  {
    id: "iv-030",
    module: "interview",
    level: 30,
    type: "match",
    question: "把「增强手段」与「解决」连线",
    pairs: [
      ["COT", "不会想→分步推理"],
      ["RAG", "不知道→查知识库"],
      ["Agent", "不会做→调工具完成任务"],
    ],
    explanation: "三者可叠加：终极 Agent 可能同时具备。",
  },
  {
    id: "iv-031",
    module: "interview",
    level: 31,
    type: "choice",
    question: "面试讲「学习态度」时，笔记提的框架最接近？",
    options: ["敢学、能学、会学 + 合作", "只刷短视频", "从不问人", "只学一天"],
    answerIndex: 0,
    explanation: "行业变化快，态度与持续学习网络都很重要。",
  },
  {
    id: "iv-032",
    module: "interview",
    level: 32,
    type: "choice",
    question: "「Scaling Law / 缩放定律」在讨论里与哪句最相关？",
    options: ["规模与性能有规律关系，但不是无脑堆就无限涨", "模型不能训练", "数据无用", "算法无用"],
    answerIndex: 0,
    explanation: "笔记提到边际与临界点：堆料与能力非简单线性。",
  },
  {
    id: "iv-033",
    module: "interview",
    level: 33,
    type: "choice",
    question: "综合：AI 训练师在「模型生命周期」里，笔记强调的主战场是？",
    options: ["只参与预训练爬数据", "后训练与应用层（SFT/RLHF/标注规则/COT/Agent/RAG 等）", "只写 PPT 封面", "只负责订盒饭"],
    answerIndex: 1,
    explanation: "多数公司用现成 base；训练师价值集中在后训练与落地数据。",
  },

  // ---------- 技能 · 入门 1-11 ----------
  {
    id: "sk-001",
    module: "skills",
    level: 1,
    type: "choice",
    question: "5W2H 中的 How Much 通常要确认什么？",
    options: ["只问天气", "预算、数据量、成本指标等", "只问颜色", "只问星座"],
    answerIndex: 1,
    explanation: "How Much：多少量、多少成本、验收指标中的量化部分。",
  },
  {
    id: "sk-002",
    module: "skills",
    level: 2,
    type: "fill",
    question: "5W2H 里，____ 表示「做什么数据集/目标」。",
    answers: ["What", "what", "WHAT"],
    explanation: "What=任务目标。",
  },
  {
    id: "sk-003",
    module: "skills",
    level: 3,
    type: "choice",
    question: "需求承接时，为什么强调「沟通留痕」？",
    options: ["为了好看", "避免事后扯皮、可对齐验收", "没必要", "只给领导看"],
    answerIndex: 1,
    explanation: "表单、确认单、问卷留痕是职业习惯。",
  },
  {
    id: "sk-004",
    module: "skills",
    level: 4,
    type: "match",
    question: "工作流顺序配对（左：环节 → 右：要点）",
    pairs: [
      ["需求承接", "5W2H + 留痕"],
      ["规则文档", "背景+概述+规则+方案"],
      ["后期交付", "统计+验收报告+复盘"],
    ],
    explanation: "五大环节：承接→规则→前期准备→中期质检→后期交付。",
  },
  {
    id: "sk-005",
    module: "skills",
    level: 5,
    type: "choice",
    question: "规则文档初版必备四大模块，哪项不属于？",
    options: ["背景 What+Why", "标注需求概述", "标注规则", "老板个人爱好"],
    answerIndex: 3,
    explanation: "背景、需求概述、标注规则、标注方案为必备框架。",
  },
  {
    id: "sk-006",
    module: "skills",
    level: 6,
    type: "fill",
    question: "试标金句：「自己不试标的训练师，写不出好____」。",
    answers: ["规则", "规则文档"],
    explanation: "必须小范围试标验证规则可执行。",
  },
  {
    id: "sk-007",
    module: "skills",
    level: 7,
    type: "choice",
    question: "一般验收合格率常见区间是？",
    options: ["60% 以下直接优秀", "95%-98% 为合格整体交付", "50% 即可", "100% 从不必要"],
    answerIndex: 1,
    explanation: "笔记：95%-98% 合格交付；不合格要回扫/二次质检。",
  },
  {
    id: "sk-008",
    module: "skills",
    level: 8,
    type: "fill",
    question: "质检抽检常见比例为标注量的 ____%-____%。（填两个数字，用英文逗号分隔，如 10,30）",
    answers: ["10,30", "10，30", "10-30", "10到30"],
    explanation: "一般质检抽检 10%-30%（笔记）。",
  },
  {
    id: "sk-009",
    module: "skills",
    level: 9,
    type: "choice",
    question: "提升单轮问答数据质量时，笔记强调重点改哪一部分？",
    options: ["只改 query 问题", "优先改 response 回答", "只改文件名", "不改"],
    answerIndex: 1,
    explanation: "「对存量单轮数据的 response 进行质量提升」——重点是回答。",
  },
  {
    id: "sk-010",
    module: "skills",
    level: 10,
    type: "choice",
    question: "数据优质四维度的优先级，安全在第几位？",
    options: ["第四", "第一（一票否决首位）", "第二", "随便"],
    answerIndex: 1,
    explanation: "安全 > 指令遵循 > 内容质量 > 语言表达（基础排序）。",
  },
  {
    id: "sk-011",
    module: "skills",
    level: 11,
    type: "match",
    question: "「问题类型」与「处理」配对",
    pairs: [
      ["response 完美", "通过"],
      ["有小问题可改", "改写"],
      ["问题严重", "舍弃"],
      ["改写难度过大", "跳过/标记"],
    ],
    explanation: "单轮处理策略：完美/改写/舍弃/跳过。",
  },

  // ---------- 技能 · 中阶 12-22 ----------
  {
    id: "sk-012",
    module: "skills",
    level: 12,
    type: "choice",
    question: "「指令遵循」里哪种算问题？",
    options: ["完全答非所问", "回答太专业", "用了 Markdown", "引用论文"],
    answerIndex: 0,
    explanation: "完全不遵循、部分遵循、无理拒答、问题有误等都属于指令维度。",
  },
  {
    id: "sk-013",
    module: "skills",
    level: 13,
    type: "fill",
    question: "SFT 三个常见项目类型：单轮问答、多轮问答、____（三个英文字母大写）。",
    answers: ["COT", "CoT"],
    explanation: "Chain of Thought 思维链数据是第三类重头项目。",
  },
  {
    id: "sk-014",
    module: "skills",
    level: 14,
    type: "choice",
    question: "RLHF 排序时，为什么常用「两两对比」？",
    options: ["因为法律规定", "人更难一次排清全局，但两两比较容易", "没有原因", "只能两个答案"],
    answerIndex: 1,
    explanation: "擂台式对比降低认知负担，推出总排序。",
  },
  {
    id: "sk-015",
    module: "skills",
    level: 15,
    type: "choice",
    question: "盲标的主要目的是？",
    options: ["让标注员互相抄", "降低互相影响、保证独立判断", "加快聊天", "减少题目"],
    answerIndex: 1,
    explanation: "质检盲标；人数常取奇数基数 3、5、7。",
  },
  {
    id: "sk-016",
    module: "skills",
    level: 16,
    type: "fill",
    question: "文本类标注任务中，规则维度「前三个固定」：安全 > ____遵循 > 内容质量；后面按项目目标调整。",
    answers: ["指令", "指令遵循"],
    explanation: "文本任务的四大维度固定排序：安全 > 指令遵循 > 内容质量 > 语言表达。注意：多模态（图片/视频）任务维度不同（如画质、图文一致性等），不能套用此排序。",
  },
  {
    id: "sk-017",
    module: "skills",
    level: 17,
    type: "choice",
    question: "多轮对话开启新项目时，为什么要「新开对话」？",
    options: ["为了费 token", "避免前序话题污染本轮逻辑", "没必要", "系统强制"],
    answerIndex: 1,
    explanation: "笔记案例：前序数学题逻辑可能串场。",
  },
  {
    id: "sk-018",
    module: "skills",
    level: 18,
    type: "choice",
    question: "标注字段里「错误类型、备注、原因」主要为了？",
    options: ["好看", "溯源与复盘有据可查", "增加工作量", "应付"],
    answerIndex: 1,
    explanation: "便于后来知道为何这样改。",
  },
  {
    id: "sk-019",
    module: "skills",
    level: 19,
    type: "fill",
    question: "汽车购买意图例子里，模型一次最多约____字以内，所以要对话切分。（填数字）",
    answers: ["2500", "二千五", "两千五"],
    explanation: "案例：2500 字上限，切分点注意语气停顿。",
  },
  {
    id: "sk-020",
    module: "skills",
    level: 20,
    type: "match",
    question: "购买意图强度与例子",
    pairs: [
      ["强意图", "主动询价、约时间"],
      ["中意图", "再考虑、和家人商量"],
      ["弱意图", "没空、再说吧"],
    ],
    explanation: "规则要写清判定+真实案例。",
  },
  {
    id: "sk-021",
    module: "skills",
    level: 21,
    type: "choice",
    question: "RAG 一条数据三要素是？",
    options: ["只有问题", "问题 + 参考材料 + 回答", "只有回答", "只有向量"],
    answerIndex: 1,
    explanation: "Question / Reference / Answer。",
  },
  {
    id: "sk-022",
    module: "skills",
    level: 22,
    type: "choice",
    question: "跳过数据的「合理理由」不包括？",
    options: ["作答成本过高", "专业能力不够改不动", "看不懂的超高难专业", "懒得看"],
    answerIndex: 3,
    explanation: "成本、能力、超范围可跳过；不能滥用跳过影响交付量。",
  },

  // ---------- 技能 · 高阶 23-33 ----------
  {
    id: "sk-023",
    module: "skills",
    level: 23,
    type: "fill",
    question: "笔记：数据错误率达到 ____%-____% 以上才较适合大量跳过（填两个数字逗号分隔）。",
    answers: ["50,70", "50，70", "50-70"],
    explanation: "否则跳太多影响交付；要控制跳过比例。",
  },
  {
    id: "sk-024",
    module: "skills",
    level: 24,
    type: "choice",
    question: "会议室 Agent 规则：用户预定时间早于当前时间应？",
    options: ["静默成功", "过期提醒，无法预订", "随机订", "打电话报警"],
    answerIndex: 1,
    explanation: "业务规则：过期提醒。",
  },
  {
    id: "sk-025",
    module: "skills",
    level: 25,
    type: "choice",
    question: "Agent 标注 8 步里，最后一步特别强调？",
    options: ["不用检查", "JSON 格式验证", "只写标题", "删除数据"],
    answerIndex: 1,
    explanation: "括号逗号错误会导致数据整条废掉。",
  },
  {
    id: "sk-026",
    module: "skills",
    level: 26,
    type: "choice",
    question: "COT 项目数据结构里，除 prompt、response 外，还要重点看哪段？",
    options: ["think 推理过程", "电脑壁纸", "鼠标速度", "文件夹颜色"],
    answerIndex: 0,
    explanation: "think + response 双优质才算过关。",
  },
  {
    id: "sk-027",
    module: "skills",
    level: 27,
    type: "match",
    question: "「向量检索」概念配对",
    pairs: [
      ["余弦相似度", "比方向接近程度"],
      ["chunk", "文档切分片段"],
      ["embedding", "文本转向量"],
    ],
    explanation: "RAG 准备阶段：切分→嵌入→入库。",
  },
  {
    id: "sk-028",
    module: "skills",
    level: 28,
    type: "choice",
    question: "写规则文档给销售同事看，哪条原则最贴切？",
    options: ["堆满理论术语", "换位思考、表格可视化、正反 case", "不写规则", "只写笑话"],
    answerIndex: 1,
    explanation: "小白视角+可视化+case；过长反而降效率。",
  },
  {
    id: "sk-029",
    module: "skills",
    level: 29,
    type: "fill",
    question: "用两段式提示词写规则文档：第一段要框架，第二段再喂____，效果更好。",
    answers: ["示例", "案例", "data", "数据示例", "样例"],
    explanation: "先框架再示例，避免一次性塞爆上下文。",
  },
  {
    id: "sk-030",
    module: "skills",
    level: 30,
    type: "choice",
    question: "项目复盘四维度不包括？",
    options: ["数据分析", "人员与推荐机制", "本次困难点", "同事鞋码"],
    answerIndex: 3,
    explanation: "数据、人员、困难点、职能能力对应。",
  },
  {
    id: "sk-031",
    module: "skills",
    level: 31,
    type: "choice",
    question: "准确率奖励举例：≥95% 可能单价乘以？",
    options: ["0.5", "1.1 或 1.2", "0", "10"],
    answerIndex: 1,
    explanation: "笔记例子：高准确率奖励；低准确率打折或不结算。",
  },
  {
    id: "sk-032",
    module: "skills",
    level: 32,
    type: "choice",
    question: "多轮标注方案里，「只标某一轮，其他轮作上下文」主要为了？",
    options: ["增加难度", "大批量提效", "删除项目", "避免用电脑"],
    answerIndex: 1,
    explanation: "全标精细但慢；单轮标适合大批量。",
  },
  {
    id: "sk-033",
    module: "skills",
    level: 33,
    type: "choice",
    question: "下列哪句最能概括 AI 训练师在团队里的核心职责？",
    options: ["只负责订会议室", "承接需求落地，为模型投喂优质语料并全流程质量管理", "只写 if-else", "不管准确率"],
    answerIndex: 1,
    explanation: "需求拆解、规则、培训试标、质检、交付复盘一体化。",
  },

  // ---------- 多选题 · 技能（5W2H、规则、维度等）----------
  {
    id: "sk-m01",
    module: "skills",
    level: 2,
    type: "multi",
    question: "5W2H 中，下列哪些属于五个「W」维度？（多选）",
    options: [
      "What：做什么、目标是什么",
      "Why：为什么做、业务价值",
      "Where：在哪用、场景",
      "When：时间节点与交付节奏",
      "Who：谁负责、谁使用",
      "How：具体方法与步骤",
      "How Much：成本与数量",
    ],
    correctIndexes: [0, 1, 2, 3, 4],
    explanation: "五个 W：What / Why / Where / When / Who；How 与 How Much 是两个 H。",
  },
  {
    id: "sk-m02",
    module: "skills",
    level: 3,
    type: "multi",
    question: "5W2H 中，下列哪些属于两个「H」？（多选）",
    options: [
      "How：具体方法、数据类型、准确率与标注规则等",
      "How Much：预算、数据量、成本与人力等「多少」",
      "When：什么时候交付",
      "Where：在哪里使用",
      "Who：谁来标注",
    ],
    correctIndexes: [0, 1],
    explanation: "2H = How + How Much；When/Where/Who 属于 W 系列里的其他维度。",
  },
  {
    id: "sk-m03",
    module: "skills",
    level: 5,
    type: "multi",
    question: "规则文档初版「必备」模块通常包括哪些？（多选）",
    options: ["背景（What + Why）", "标注需求概述", "标注规则（核心）", "标注方案（线上/线下与平台）", "老板个人爱好随笔"],
    correctIndexes: [0, 1, 2, 3],
    explanation: "背景、需求概述、规则、方案为初版必备四大块。",
  },
  {
    id: "sk-m04",
    module: "skills",
    level: 4,
    type: "multi",
    question: "笔记里「模型训练三要素」包括哪些？（多选）",
    options: ["算力（如 GPU）", "算法/架构（如 Transformer）", "高质量数据", "办公室绿植品种"],
    correctIndexes: [0, 1, 2],
    explanation: "算力 + 算法 + 数据；金句：吃什么就拉什么。",
  },
  {
    id: "sk-m05",
    module: "skills",
    level: 12,
    type: "multi",
    question: "SFT 阶段常见的三大类训练数据项目是？（多选）",
    options: ["单轮问答", "多轮问答", "COT 思维链", "只做预训练爬全网", "只写会议纪要"],
    correctIndexes: [0, 1, 2],
    explanation: "SFT 常见项目：单轮、多轮、COT；预训练是更前一阶段。",
  },
  {
    id: "sk-m06",
    module: "skills",
    level: 11,
    type: "multi",
    question: "「内容质量」维度下，笔记列出的五个小项包括哪些？（多选）",
    options: ["准确性", "价值丰富度", "贴切性", "时效性", "权威性", "话术冗余（多属语言维度）"],
    correctIndexes: [0, 1, 2, 3, 4],
    explanation: "内容维度：准确、丰富、贴切、时效、权威；话术/格式等更偏语言维度。",
  },
  {
    id: "sk-m07",
    module: "skills",
    level: 18,
    type: "multi",
    question: "项目复盘时，笔记建议重点复盘哪些维度？（多选）",
    options: ["数据分析（交付量、差数据等）", "人员分析（优秀者推荐等）", "本次任务困难点", "对应职能与解决问题能力", "同事鞋码"],
    correctIndexes: [0, 1, 2, 3],
    explanation: "复盘四维度：数据、人员、困难点、职能能力。",
  },
  {
    id: "sk-m08",
    module: "skills",
    level: 8,
    type: "multi",
    question: "需求承接用 5W2H 沟通时，通常需要量化或对齐的有哪些？（多选）",
    options: ["When：交付节点与排期", "How Much：预算、数据量、成本", "How：数据类型、准确率、标注方式", "What：任务目标与数据集", "只问星座运势"],
    correctIndexes: [0, 1, 2, 3],
    explanation: "What/Why/Where/When/Who/How/How Much 都要落到可执行信息；How Much 与 When 最易被忽略。",
  },

  // ---------- 多选题 · 面试 ----------
  {
    id: "iv-m01",
    module: "interview",
    level: 6,
    type: "multi",
    question: "笔记总结的「AI 五大热门就业方向」包括哪些？（多选）",
    options: ["多模态", "Agent", "自动驾驶", "具身智能", "解决方案专家", "只做 Excel 表"],
    correctIndexes: [0, 1, 2, 3, 4],
    explanation: "多模态、Agent、自动驾驶、具身智能、解决方案专家。",
  },
  {
    id: "iv-m02",
    module: "interview",
    level: 7,
    type: "multi",
    question: "预训练阶段里，AI 训练师「更可能参与」的前两个环节是？（多选）",
    options: ["数据收集", "数据预处理（清洗分类等）", "分词与神经网络训练推理（多为算法主导）", "给显卡贴膜"],
    correctIndexes: [0, 1],
    explanation: "训练师多在数据收集与预处理有参与；分词与训练推理通常算法主导。",
  },
  {
    id: "iv-m03",
    module: "interview",
    level: 9,
    type: "multi",
    question: "关于大模型按 Token 计费，下列哪些说法是对的？（多选）",
    options: ["输入 token 要计费", "输出 token 也要计费", "中英文等语言的切分与 token 数不同", "按鼠标点击次数计费"],
    correctIndexes: [0, 1, 2],
    explanation: "输入输出都计费；不同语言 token 化不同；便于感知模型价值与成本。",
  },
  {
    id: "iv-m04",
    module: "interview",
    level: 11,
    type: "multi",
    question: "Agent 的三大核心能力包括？（多选）",
    options: ["规划 Planning", "记忆 Memory", "工具调用 Tools", "替用户睡觉"],
    correctIndexes: [0, 1, 2],
    explanation: "规划、记忆、工具调用是 Agent 相对纯聊天 LLM 的关键增量。",
  },
  {
    id: "iv-m05",
    module: "interview",
    level: 15,
    type: "multi",
    question: "RAG 能解决或缓解的典型问题包括？（多选）",
    options: ["企业私有知识「模型不知道」", "专业领域政策/手册落地", "训练截止时间之后的信息更新", "显卡驱动冲突"],
    correctIndexes: [0, 1, 2],
    explanation: "外挂知识库补缺失与专业、时效；不能解决所有幻觉类型。",
  },

  // ============================================================
  // 第一周补充题 · 判断题（面试模块）
  // ============================================================
  {
    id: "iv-tf01",
    module: "interview",
    level: 3,
    type: "truefalse",
    question: "Transformer 架构是 2017 年由 Google 在论文《Attention is All You Need》中提出的。",
    correct: true,
    explanation: "正确。Transformer 是 2017 年 Google 提出，是当前几乎所有大模型（GPT/Claude/DeepSeek）的底层架构，核心是自注意力机制（Self-Attention）。",
  },
  {
    id: "iv-tf02",
    module: "interview",
    level: 5,
    type: "truefalse",
    question: "DeepSeek 以大量 AI 训练师岗位著称，数据标注通常都是内部完成，不会外包。",
    correct: false,
    explanation: "错误。笔记明确：DeepSeek 工种几乎都是工程师，数据训练通常「外包」给数据标注公司，这也是 AI 训练师的重要就业场景。",
  },
  {
    id: "iv-tf03",
    module: "interview",
    level: 7,
    type: "truefalse",
    question: "「幻觉」是指 AI 模型一本正经地胡说八道，生成不符合事实或凭空捏造的内容。",
    correct: true,
    explanation: "正确。幻觉三大成因：①训练数据本身错误 ②领域数据缺失 ③Token 逐词预测链式走错，模型会自圆其说一路编下去。",
  },
  {
    id: "iv-tf04",
    module: "interview",
    level: 9,
    type: "truefalse",
    question: "预训练（Pre-training）阶段，模型通过大量「人工标注数据」进行有监督学习。",
    correct: false,
    explanation: "错误！预训练是「无监督学习」——把全网数据一股脑塞给模型，模型自己学规律，人不干预。产出的是 base model（裸模型）。",
  },
  {
    id: "iv-tf05",
    module: "interview",
    level: 10,
    type: "truefalse",
    question: "Zero-shot COT 只需在提示词里加一句「让我们一步步思考」就能触发模型分步推理，不需要修改模型参数。",
    correct: true,
    explanation: "正确。Zero-shot COT 是最轻量的方式，一句提示词即可触发推理，完全不改模型本身。SFT/RLHF 版 COT 才需要训练。",
  },
  {
    id: "iv-tf06",
    module: "interview",
    level: 14,
    type: "truefalse",
    question: "RAG（检索增强生成）可以彻底解决所有类型的 AI 幻觉问题。",
    correct: false,
    explanation: "错误。RAG 主要解决「数据缺失」导致的幻觉（模型不知道）。「训练数据本身错误」和「概率预测链式走错」这两类幻觉，RAG 解决不了。",
  },
  {
    id: "iv-tf07",
    module: "interview",
    level: 16,
    type: "truefalse",
    question: "RAG 中 Top-K 值越大，召回内容越全面，模型回答质量就越高。",
    correct: false,
    explanation: "错误！K 值过大会导致模型「注意力稀释」，反而答得更差。笔记金句：「模型输入内容越多，生成结果越烂。」",
  },
  {
    id: "iv-tf08",
    module: "interview",
    level: 18,
    type: "truefalse",
    question: "COT 思维链会消耗更多计算资源，对简单问题开启 COT 反而拖慢速度、浪费成本。",
    correct: true,
    explanation: "正确。COT 缺点：吃显存、成本高。对「今天几号」这类简单问题开 COT 是浪费，所以现代模型（如 DeepSeek R1）让用户自选是否开启思考模式。",
  },
  {
    id: "iv-tf09",
    module: "interview",
    level: 20,
    type: "truefalse",
    question: "「过拟合」是指模型在训练数据上学得太死，换新题型就懵，泛化能力差。",
    correct: true,
    explanation: "正确。过拟合 = 死记硬背的学生，训练题全对，换题型就不会。解决方法：增加数据量和多样性。欠拟合则反过来——连训练题都做不对。",
  },
  {
    id: "iv-tf10",
    module: "interview",
    level: 22,
    type: "truefalse",
    question: "多模态中，「扩散模型（Diffusion Model）」最适合文字渲染准确、海报设计等精确文字场景。",
    correct: false,
    explanation: "错误！适合文字渲染、海报设计的是「自回归模型」（如 DALL-E、GPT-4o 图像部分）。扩散模型（SD、Flux）更擅长真实感图像和艺术风格。",
  },
  {
    id: "iv-tf11",
    module: "interview",
    level: 25,
    type: "truefalse",
    question: "Embedding（向量化）的核心特性是：语义相近的词/句，对应的向量在数值上也越接近。",
    correct: true,
    explanation: "正确！这是 RAG 能工作的基础。「苹果」和「Apple」向量很近；「苹果」和「汽车」向量很远。语义距离 ≈ 向量距离，用余弦相似度衡量。",
  },

  // ============================================================
  // 排序题（面试模块）
  // ============================================================
  {
    id: "iv-ord01",
    module: "interview",
    level: 8,
    type: "order",
    question: "将「大语言模型训练全流程」按正确顺序排列：",
    steps: [
      "① 收集海量数据（全网文本/代码/论文）",
      "② 硬件运算（GPU集群高速计算）",
      "③ 算法投喂（Transformer架构指导学习）",
      "④ 测试测验（给模型出题打分）",
      "⑤ 迭代优化（补数据、调参数）",
    ],
    explanation: "海量数据 → 硬件运算 → 算法投喂 → 测试测验 → 迭代优化。AI训练师主要参与「数据准备」和「测试评估」环节。",
  },
  {
    id: "iv-ord02",
    module: "interview",
    level: 13,
    type: "order",
    question: "将「后训练阶段」按正确顺序排列：",
    steps: [
      "① base model（预训练完的裸模型）",
      "② SFT 有监督微调（教模型做事）",
      "③ RLHF 强化学习（教模型做得更好）",
      "④ 可上线使用的 AI 助手",
    ],
    explanation: "先有 base model → SFT 教「做对」→ RLHF 教「做更好」→ 最终得到可用的 AI 助手。SFT 永远在 RLHF 之前。",
  },
  {
    id: "iv-ord03",
    module: "interview",
    level: 18,
    type: "order",
    question: "将「RAG 运行阶段」按正确顺序排列：",
    steps: [
      "① 用户发出 query（提问）",
      "② embedding 模型将 query 转成向量",
      "③ 向量数据库检索最相似的 chunk",
      "④ 构建「原始 query + 召回内容」的增强 prompt",
      "⑤ 大模型基于增强 prompt 生成答案",
    ],
    explanation: "用户提问 → 向量化 → 检索 → 构建增强 prompt → 生成答案。Embedding 是 RAG 能工作的关键桥梁。",
  },
  {
    id: "iv-ord04",
    module: "interview",
    level: 21,
    type: "order",
    question: "将「ReAct 框架循环步骤」按正确顺序排列：",
    steps: [
      "① Thought：我需要做什么？（思考规划）",
      "② Action：调用工具/执行操作",
      "③ Observation：观察工具返回结果",
      "④ 判断：任务完成？继续循环 or 输出最终答案",
    ],
    explanation: "ReAct = Reasoning + Acting。循环：思考 → 行动 → 观察 → 再思考。Agent 不一条道走到黑，能自我纠错。",
  },

  // ============================================================
  // 知识点补充题（面试模块）
  // ============================================================
  {
    id: "iv-n01",
    module: "interview",
    level: 4,
    type: "choice",
    question: "关于 Token 计费，下列说法正确的是？",
    options: [
      "只有输出内容才按 token 计费",
      "输入 token 和输出 token 都会计费，价格通常不同",
      "中文每个汉字 = 1 个 token",
      "token 费用和模型回答长度无关",
    ],
    answerIndex: 1,
    explanation: "输入（你的提问）和输出（模型回答）都按 token 计费。中文 1 汉字 ≈ 1.5-2 个 token，不是 1 个。不同模型价格不同，DeepSeek 约是 GPT-4o 的 1/10。",
  },
  {
    id: "iv-n02",
    module: "interview",
    level: 6,
    type: "fill",
    question: "1000 个中文汉字大约等于多少个 token？（填数字范围，格式：如 1500-2000）",
    answers: ["1500-2000", "1500～2000", "1500~2000", "1500到2000"],
    explanation: "中文 1 汉字 ≈ 1.5-2 个 token，1000 字 ≈ 1500-2000 token。这是估算 API 成本的关键数据。",
  },
  {
    id: "iv-n03",
    module: "interview",
    level: 8,
    type: "match",
    question: "将「AI 三种学习方式」与「特点/代表」连线：",
    pairs: [
      ["规则模型", "写死 if-else，早期语音助手"],
      ["机器学习", "人工总结规律，天气预测"],
      ["深度学习", "自主从数据学习，GPT/Claude"],
    ],
    explanation: "三代演进：规则（写死）→ 机器学习（人总结）→ 深度学习（自主学）。当前大模型 = 深度学习 + Transformer。",
  },
  {
    id: "iv-n04",
    module: "interview",
    level: 11,
    type: "choice",
    question: "什么是模型的「涌现（Emergence）」？",
    options: [
      "参数减少时模型突然变快",
      "数据/算力/算法堆叠到临界点后，模型突然出现之前没有的新能力",
      "模型出现幻觉的技术原因",
      "数据清洗过程中的一种技术",
    ],
    answerIndex: 1,
    explanation: "涌现 = 武侠里打通任督二脉。规模堆到临界点，能力跃迁式出现（如 GPT-3→4 突然出现高阶推理）。研究员事先也无法预测。",
  },
  {
    id: "iv-n05",
    module: "interview",
    level: 13,
    type: "choice",
    question: "SFT（有监督微调）的核心逻辑是？",
    options: [
      "把全网无标注数据一股脑塞给模型，让它自学",
      "精选「标准答案」数据投喂模型，让它学会特定任务的回答套路",
      "让模型自主产生反馈并强化训练",
      "调整模型的 GPU 分配策略",
    ],
    answerIndex: 1,
    explanation: "SFT = 教模型「这种回答是对的」。类比：想让模型讲好笑话，就喂一批高质量笑话数据给它学套路。SFT 在 RLHF 之前。",
  },
  {
    id: "iv-n06",
    module: "interview",
    level: 15,
    type: "multi",
    question: "COT（思维链）的主要优点包括哪些？（多选）",
    options: [
      "提高复杂推理的准确率",
      "增加用户对回答的信任感（看到推理过程）",
      "能完全消除 AI 幻觉",
      "便于定位错误步骤，方便针对性改写",
      "降低所有场景的计算成本",
    ],
    correctIndexes: [0, 1, 3],
    explanation: "COT 三大优点：①提高准确率 ②增加信任感 ③便于纠错。但 COT 不能消除幻觉，也不降低成本（反而更贵），简单问题不建议开。",
  },
  {
    id: "iv-n07",
    module: "interview",
    level: 17,
    type: "match",
    question: "将三大「增强大模型能力的手段」连线：",
    pairs: [
      ["COT 思维链", "让模型「会推理」——解决不会想"],
      ["RAG 检索增强", "让模型「会查资料」——解决不知道"],
      ["Agent 智能体", "让模型「会做事」——解决不会做"],
    ],
    explanation: "三者可叠加！终极形态 = Agent（会做事）+ RAG（会查资料）+ COT（会推理）。这就是现在顶级 AI 系统的架构。",
  },
  {
    id: "iv-n08",
    module: "interview",
    level: 19,
    type: "choice",
    question: "ReAct 框架的循环步骤正确顺序是？",
    options: [
      "Action → Thought → Observation",
      "Thought → Action → Observation",
      "Observation → Action → Thought",
      "Thought → Observation → Action",
    ],
    answerIndex: 1,
    explanation: "ReAct = Reasoning + Acting。循环：Thought（思考要做什么）→ Action（调用工具）→ Observation（观察结果）→ 继续或给答案。",
  },
  {
    id: "iv-n09",
    module: "interview",
    level: 21,
    type: "choice",
    question: "多模态中，「扩散模型（Diffusion Model）」的核心原理一句话是？",
    options: [
      "把图片切成小方格，像写文章一样逐块预测下一块",
      "先把图片「打碎」成噪点，再一步步「还原」出新图片",
      "通过语音识别将声音转为图像",
      "把文字直接映射到像素矩阵",
    ],
    answerIndex: 1,
    explanation: "扩散 = 先加噪声（打碎）→ 去噪声（还原）。类比：白纸泼墨→一点点擦干净→出现你想要的图。代表：Stable Diffusion、Flux、Seedream（字节）。",
  },
  {
    id: "iv-n10",
    module: "interview",
    level: 23,
    type: "choice",
    question: "MCP（Model Context Protocol）的核心作用是什么？",
    options: [
      "替代 GPU 进行模型训练",
      "统一 APP 接口规范，让 AI 工具能调用其他软件（Chrome、飞书等）",
      "给模型添加长期记忆功能",
      "提高 Token 处理速度",
    ],
    answerIndex: 1,
    explanation: "MCP = 上下文协议，是工具间通信的桥梁。让 Cursor 能调 Chrome、飞书、Blender 等软件。CLI 比 MCP 权限更高，是更新的趋势。",
  },
  {
    id: "iv-n11",
    module: "interview",
    level: 26,
    type: "fill",
    question: "RAG 的英文全称展开是什么？（填英文全称）",
    answers: ["Retrieval-Augmented Generation", "Retrieval Augmented Generation"],
    explanation: "RAG = Retrieval-Augmented Generation（检索增强生成）。外挂知识库让模型回答更准、更新、更专业。",
  },
  {
    id: "iv-n12",
    module: "interview",
    level: 28,
    type: "choice",
    question: "「上下文工程师（CE）」相比传统「提示词工程师（PE）」，最大的区别在于？",
    options: [
      "CE 只写英文提示词",
      "CE 的核心是管理上下文（参考资料/Memory/历史对话），而不只是写提示词",
      "CE 不需要了解 AI 原理",
      "CE 主要做数据标注工作",
    ],
    answerIndex: 1,
    explanation: "PE 只写单次提示词；CE 管理整个上下文输入：参考资料 + 系统提示词 + Memory 文档 + 历史对话。CE 是 AI 时代更高级的岗位。",
  },

  // ============================================================
  // 判断题（技能模块）
  // ============================================================
  {
    id: "sk-tf01",
    module: "skills",
    level: 3,
    type: "truefalse",
    question: "规则文档中，「项目背景（What + Why）」是辅助内容，可以省略不写。",
    correct: false,
    explanation: "错误！背景是规则文档 4 大「必备内容」之一：①背景 ②标注需求概述 ③标注规则 ④标注方案。缺少背景，标注员不了解为什么做，容易出错。",
  },
  {
    id: "sk-tf02",
    module: "skills",
    level: 5,
    type: "truefalse",
    question: "文本类数据标注 4 大维度的优先级：安全 > 指令遵循 > 内容质量 > 语言表达。",
    correct: true,
    explanation: "正确！（文本任务）安全永远排第一（一票否决），然后指令遵循，再内容质量，最后语言表达。注意：图片/视频等多模态任务维度不同（如图文一致性、画质、美感等），不能套用此排序。",
  },
  {
    id: "sk-tf03",
    module: "skills",
    level: 7,
    type: "truefalse",
    question: "数据标注时，只要觉得这条数据改写麻烦，就可以选择跳过。",
    correct: false,
    explanation: "错误！「数据错误率达到 50%-70% 以上」才合理跳过。因为数据量有限，滥用跳过会导致交付量不足。合理理由：①改写成本过高 ②超出专业能力 ③安全类直接舍弃。",
  },
  {
    id: "sk-tf04",
    module: "skills",
    level: 9,
    type: "truefalse",
    question: "质检工作需要对全量标注数据进行 100% 逐条检查，才能保证交付质量。",
    correct: false,
    explanation: "错误。质检一般「抽检 10%-30%」，全量检查成本过高。关键是抽检比例合理、流程规范，发现问题后二次质检补足。",
  },
  {
    id: "sk-tf05",
    module: "skills",
    level: 11,
    type: "truefalse",
    question: "多轮对话中，第二轮回答可以用「她」指代第一轮出现的人名，这是正常的「指代省略」，不算问题。",
    correct: true,
    explanation: "正确。多轮对话三大特有规则之一：指代省略——后续轮可用代词指代前文内容，不必每轮重复全名。但模型必须准确理解指代关系。",
  },
  {
    id: "sk-tf06",
    module: "skills",
    level: 13,
    type: "truefalse",
    question: "COT 标注中，「嗯让我想想……也可能是……我再确认下……」这类表达属于高质量的有效反思。",
    correct: false,
    explanation: "错误！这是无效反思，属于冗余废话。有效反思 = 具体指出哪里错了并重新推导，如「等等，我前面 23×4 算成了 96，应该是 92，重新算……」。",
  },
  {
    id: "sk-tf07",
    module: "skills",
    level: 15,
    type: "truefalse",
    question: "RLHF 排序时，3 个标注员意见不一致，应取得分最高的答案作为最终结果。",
    correct: false,
    explanation: "错误！3 人不一致要继续增加标注员直到达成「多数一致」（如 2:1），或开会讨论。不能简单取最高分——排序的主观性需要多人共识来平衡。",
  },
  {
    id: "sk-tf08",
    module: "skills",
    level: 17,
    type: "truefalse",
    question: "「盲标」是指标注员在标注时不能看到其他人的标注结果，以保证各自判断的独立性。",
    correct: true,
    explanation: "正确。盲标的目的是减少「从众效应」和主观影响。质检通常采用盲标，人数以奇数为宜（3、5、7……），出现分歧再增加人数。",
  },

  // ============================================================
  // 排序题（技能模块）
  // ============================================================
  {
    id: "sk-ord01",
    module: "skills",
    level: 6,
    type: "order",
    question: "将「AI 训练师完整工作流」按正确顺序排列：",
    steps: [
      "① 需求承接（用 5W2H 沟通确认）",
      "② 规则文档撰写（初版 + 试标）",
      "③ 标注前期准备（培训人员 + 试标筛人）",
      "④ 中期作业与质检（任务分配 + Badcase 分析）",
      "⑤ 后期交付复盘（数据统计 + 撰写报告）",
    ],
    explanation: "需求承接 → 规则文档 → 前期准备 → 中期质检 → 后期交付。AI 训练师是全流程管理者，每一步都要主导。",
  },
  {
    id: "sk-ord02",
    module: "skills",
    level: 12,
    type: "order",
    question: "将「规则文档从初版到定稿」的优化流程按正确顺序排列：",
    steps: [
      "① 与需求方对接，沟通并留痕",
      "② 撰写初版规则文档",
      "③ 自己 + 少量同事小规模试标",
      "④ 分析标注质量、处理 Badcase",
      "⑤ 双方达标后，细化正式文档",
    ],
    explanation: "先沟通 → 写初版 → 试标验证 → 分析改进 → 定稿。金句：「自己不试标的训练师，写不出好规则。」",
  },
  {
    id: "sk-ord03",
    module: "skills",
    level: 18,
    type: "order",
    question: "将「Agent 标注工作步骤」按正确顺序排列：",
    steps: [
      "① 阅读项目背景文档",
      "② 理解每个工具的定义和能力范围",
      "③ 检查 user prompt 是否合理清晰",
      "④ 检查并改写不合理的 think/action",
      "⑤ JSON 格式验证（避免括号/逗号错误）",
    ],
    explanation: "先理解背景和工具 → 检查输入 → 改写优化 → 格式验证。JSON 格式验证是最后一关，格式错误会让整条数据废掉。",
  },

  // ============================================================
  // 知识点补充题（技能模块）
  // ============================================================
  {
    id: "sk-n01",
    module: "skills",
    level: 4,
    type: "choice",
    question: "安全维度的数据不通过，正确处理方式是？",
    options: [
      "改写修正后可以使用",
      "降低分数但保留",
      "直接舍弃，一票否决",
      "标记为待确认，交给上级处理",
    ],
    answerIndex: 2,
    explanation: "安全维度 = 一票否决！涉政、涉法、黄赌毒、违反价值观 → 必须直接舍弃。这是 4 大维度中优先级最高、最严格的一条。",
  },
  {
    id: "sk-n02",
    module: "skills",
    level: 6,
    type: "multi",
    question: "文本类任务中，「内容质量维度」包含哪 5 个子维度？（多选）",
    options: ["准确性", "价值丰富度", "语言流畅性", "贴切性", "时效性", "权威性"],
    correctIndexes: [0, 1, 3, 4, 5],
    explanation: "内容 5 子维度：准确性、价值丰富度、贴切性、时效性、权威性。注意：「语言流畅性」属于语言维度，别混淆！",
  },
  {
    id: "sk-n03",
    module: "skills",
    level: 8,
    type: "choice",
    question: "RLHF 排序时为什么推荐「两两对比」而不是直接给每个答案打 1-10 分？",
    options: [
      "两两对比花费时间更少",
      "直接打分不符合平台规定",
      "两两对比比绝对打分更容易判断，能有效减少主观偏差",
      "打 1-10 分会引起版权纠纷",
    ],
    answerIndex: 2,
    explanation: "类比找对象：你很难直接说出「我想要什么」的绝对排名，但「A 和 B 你更喜欢哪个」就容易。两两对比减少个人主观偏差，提高一致性。",
  },
  {
    id: "sk-n04",
    module: "skills",
    level: 10,
    type: "fill",
    question: "标注准确率达到 ≥95% 时，标注员获得奖励计费，奖励系数是多少？（格式：如「1.1 或 1.2」）",
    answers: ["1.1或1.2", "1.1 或 1.2", "1.1~1.2", "1.1-1.2"],
    explanation: "准确率激励：≥95% → ×1.1 或 1.2（奖励）；80-95% → 标准价；70-80% → ×0.75（打折）；<70% → 不予结算。",
  },
  {
    id: "sk-n05",
    module: "skills",
    level: 14,
    type: "choice",
    question: "COT 标注数据由哪三部分构成？",
    options: [
      "query（问题）+ answer（答案）",
      "prompt（问题）+ think（推理过程）+ response（答案）",
      "title + content + metadata",
      "user_input + system_prompt + output",
    ],
    answerIndex: 1,
    explanation: "COT 数据三件套：prompt（用户问题）+ think（模型推理过程）+ response（最终答案）。训练师需同时标注 think 和 response 两部分质量。",
  },
  {
    id: "sk-n06",
    module: "skills",
    level: 16,
    type: "fill",
    question: "RAG 标注数据的 3 要素是什么？（用「+」连接，格式：如「A+B+C」）",
    answers: ["问题+参考材料+回答", "问题+参考+回答", "Question+Reference+Answer", "Q+R+A"],
    explanation: "RAG 一条数据 = 问题（Question）+ 参考材料（Reference）+ 回答（Answer）。三者缺一不可，是评判 RAG 标注质量的基础单元。",
  },
  {
    id: "sk-n07",
    module: "skills",
    level: 19,
    type: "multi",
    question: "以下哪些情况可以「合理选择跳过」一条标注数据？（多选）",
    options: [
      "改写成本极高，需要大量专业知识支撑",
      "数据涉及安全红线（涉政/黄赌毒）",
      "超出自己专业能力范围（如量子物理）",
      "数据格式稍微不规范（如空格多了一个）",
      "数据文字太长，读起来费力",
    ],
    correctIndexes: [0, 1, 2],
    explanation: "合理跳过三类：①改写成本过高 ②安全类（直接舍弃）③超出能力范围。格式小问题和数据长都不是跳过理由，要解决不要逃避！",
  },
  {
    id: "sk-n08",
    module: "skills",
    level: 21,
    type: "match",
    question: "将「验收准确率」与「对应处理方式」连线：",
    pairs: [
      ["≥ 95%（合格）", "整体交付，撰写交付报告"],
      ["80% - 95%", "标准计费，正常交付"],
      ["< 70%（严重不合格）", "不予结算，考虑重新找人"],
    ],
    explanation: "准确率激励机制：≥95% 奖励 → 80-95% 标准 → 70-80% 打折 → <70% 不结算。明确规则，让标注员有动力维持高质量。",
  },
  {
    id: "sk-n09",
    module: "skills",
    level: 24,
    type: "choice",
    question: "用大模型辅助撰写规则文档时，「两段式提示词法」的正确做法是？",
    options: [
      "一次性把所有需求和数据都发给模型，得到完整文档",
      "先让模型了解项目大概并产出框架，再基于示例数据输出完整规则",
      "直接让模型生成规则，不需要提供任何背景",
      "先发数据，再问模型为什么要做这个项目",
    ],
    answerIndex: 1,
    explanation: "两段式：①让模型了解项目 + 获得框架 → ②把示例数据 + 约束条件发给模型 → 输出完整规则文档。分段对话比一次性塞入效果更好。",
  },

  // ============================================================
  // 第三周补充题 · 多模态质检维度（技能模块）
  // ============================================================
  {
    id: "mm-c01",
    module: "skills",
    level: 8,
    type: "choice",
    question: "多模态图片生成类项目中，评测的核心三个维度是？",
    options: [
      "安全 > 指令遵循 > 内容质量（和文本任务一样）",
      "情景契合度、元素匹配度、美感",
      "字准率、句准率、流利度",
      "分辨率、帧率、比特率",
    ],
    answerIndex: 1,
    explanation: "图片生成评测三维度：①情景契合度（画面与提示词是否匹配）②元素匹配度（要素是否完整）③美感。与文本四维度（安全/指令/内容/语言）完全不同，要注意区分。",
  },
  {
    id: "mm-c02",
    module: "skills",
    level: 6,
    type: "choice",
    question: "多模态图片筛选项目中，下列哪类图片需要直接标注「跳过」？",
    options: [
      "颜色偏暖、构图偏右的图",
      "画面过曝/过暗导致主体无法辨识的图",
      "主体是单一物体的图",
      "使用三分构图的图",
    ],
    answerIndex: 1,
    explanation: "图片筛选7类「跳过」标准：安全性问题、内容不符合需求、异常画面（黑框截图等）、多图拼接、画面模糊、过曝/过暗、无美感随机构图。过曝/过暗影响主体辨识，直接跳过。",
  },
  {
    id: "mm-c03",
    module: "skills",
    level: 9,
    type: "choice",
    question: "在图片描述（Caption）项目中，「第一步：打标签」主要标注的维度不包括哪项？",
    options: ["色调（暖/冷）", "拍摄角度（仰拍/俯拍等）", "图片文件大小（KB）", "景别（全景/近景/特写等）"],
    answerIndex: 2,
    explanation: "Caption打标签维度：色调、拍摄角度、构图方式、景别、光影、焦距。「文件大小」是技术参数，不是Caption标签维度。",
  },
  {
    id: "mm-f01",
    module: "skills",
    level: 7,
    type: "fill",
    question: "图片Caption标准公式：主体描述 + ____词 + 细节补充 + 艺术风格。",
    answers: ["修饰", "修饰词"],
    explanation: "Caption四要素：主体描述（是什么/谁）+ 修饰词（表情/动作/材质/颜色）+ 细节补充（背景/装饰）+ 艺术风格（情绪氛围）。",
  },
  {
    id: "mm-c04",
    module: "skills",
    level: 10,
    type: "choice",
    question: "VLM（视觉语言模型）项目的数据形式是？",
    options: [
      "图片 + 分类标签",
      "图片 + 问题 + 答案（三件套）",
      "图片 + 音频",
      "图片 + 提示词关键词",
    ],
    answerIndex: 1,
    explanation: "VLM项目数据固定三件套：图片 + 问题 + 答案。标注员要先做有效性判断（图片/问题是否合规），再做答案正确性判定（对→保留，错→改写，质量差→也要改写）。",
  },
  {
    id: "mm-tf01",
    module: "skills",
    level: 8,
    type: "truefalse",
    question: "自回归模型（如DALL-E、GPT-4o图像）比扩散模型更擅长生成文字准确的海报和UI图。",
    correct: true,
    explanation: "正确！自回归模型逐像素块预测，文字渲染准确性高、指令遵循强，适合海报/UI图。扩散模型整体去噪，艺术创作强但文字容易乱。面试区分考点。",
  },
  {
    id: "mm-c05",
    module: "skills",
    level: 12,
    type: "choice",
    question: "ASR（自动语音识别）项目中，「字准率」的含义是？",
    options: [
      "模型识别出的文字里，有多少是正确的（单字正确率）",
      "完整句子识别正确的比例",
      "识别速度（字/秒）",
      "文件格式的压缩率",
    ],
    answerIndex: 0,
    explanation: "ASR两大核心指标：字准率（单字正确率）+ 句准率（整句正确率）。字准率看字，句准率看整句——两个都低说明模型基础很差。",
  },
  {
    id: "mm-tf02",
    module: "skills",
    level: 6,
    type: "truefalse",
    question: "ASR转写规则要求：转写结果需要加上标准的标点符号，让文本更易读。",
    correct: false,
    explanation: "错误！ASR转写规则明确：不加任何标点符号。原则是「说了什么写什么」，不省略、不补充，语气词加口字旁（嗯/啊），平翘舌不纠正，完全忠实于原始语音。",
  },
  {
    id: "mm-c06",
    module: "skills",
    level: 14,
    type: "choice",
    question: "多模态项目中，视频标注相比图片标注额外增加的描述内容是？",
    options: [
      "颜色分析和饱和度",
      "镜头运动描述（推/拉/摇/移等）",
      "文件格式和帧率",
      "上传平台和存储路径",
    ],
    answerIndex: 1,
    explanation: "视频Caption在图片基础上额外加：镜头运动描述（推、拉、摇、移、升、降）和帧间连贯性判断。视频是连续图片，流畅度是额外的质量维度。",
  },
  {
    id: "mm-multi01",
    module: "skills",
    level: 10,
    type: "multi",
    question: "图片筛选项目中，需要标注「跳过」的情况包括哪些？（多选）",
    options: ["安全问题（黄赌毒/涉政）", "画面模糊（运动/对焦模糊）", "多图拼接（手机截图等）", "无美感的随机构图", "颜色偏暖的图"],
    correctIndexes: [0, 1, 2, 3],
    explanation: "跳过7类：安全性、内容不符、异常画面（黑白框/截图）、多图拼接、模糊、过曝/过暗、无美感构图。「颜色偏暖」是正常图片，不跳过。",
  },
  {
    id: "mm-ord01",
    module: "skills",
    level: 12,
    type: "order",
    question: "多模态生成类项目的完整流程，按正确顺序排列：",
    steps: [
      "① 数据筛选（剔除低质量/安全问题图片）",
      "② 数据分类（按风格/内容/主体等归类）",
      "③ 数据描述 Caption（把图片内容转成文字）",
      "④ 模型训练（投喂数据）",
      "⑤ 数据评测（评估生成效果）",
    ],
    explanation: "筛选→分类→描述→训练→评测。AI训练师前期「选食材、分类、写菜谱」，后期「品菜评分」。",
  },

  // ============================================================
  // ComfyUI + LoRA 训练实战（技能模块）
  // ============================================================
  {
    id: "cu-c01",
    module: "skills",
    level: 15,
    type: "choice",
    question: "ComfyUI 中，CLIP 编码器的核心作用是？",
    options: [
      "把潜在空间里的图像解码成像素级图像",
      "把文字描述（提示词）翻译成模型能理解的向量",
      "控制扩散步骤数和采样策略",
      "对输入图像进行压缩编码",
    ],
    answerIndex: 1,
    explanation: "CLIP = 模型的「翻译官」，把自然语言提示词转成模型语言（向量）。VAE才是图像编解码器；K采样器控制步数和策略。",
  },
  {
    id: "cu-c02",
    module: "skills",
    level: 15,
    type: "choice",
    question: "ComfyUI 七节点工作流中，「潜在空间」（Latent Space）里的图像最终要经过哪个节点才能变成人眼可见的图片？",
    options: ["CLIP 文本编码器", "K 采样器", "VAE 解码器", "空 Latent 节点"],
    answerIndex: 2,
    explanation: "工作流路径：CLIP编码词条→K采样器在潜在空间去噪→VAE解码器还原成像素图→预览/保存。VAE解码器是「出图」的最后一步。",
  },
  {
    id: "cu-c03",
    module: "skills",
    level: 16,
    type: "choice",
    question: "SD 1.5 模型的训练数据分辨率是 512×512，如果生成图时空 Latent 设置成 1024×1024，会发生什么？",
    options: ["图像更清晰", "画面崩坏（结构混乱）", "自动降采样正常输出", "无影响"],
    answerIndex: 1,
    explanation: "SD 1.5 只支持 512×512，超出训练分辨率会画面崩坏。Flux 模型支持 1024×1024 及以上。这是实操中最常见的踩坑点。",
  },
  {
    id: "cu-c04",
    module: "skills",
    level: 17,
    type: "choice",
    question: "LoRA 模型的本质是什么？",
    options: [
      "完整的独立大模型，可以单独运行",
      "在大模型上叠加的「风格插件」，训练量少、针对性强",
      "用于替换 Checkpoint 的底模",
      "ComfyUI 的工作流模板",
    ],
    answerIndex: 1,
    explanation: "LoRA = 大模型上的「插件」，只需 15-30 张图即可训练，针对特定风格/主体效果强，可叠加多个。在 LibLib 可直接搜索和使用他人训练好的 LoRA。",
  },
  {
    id: "cu-f01",
    module: "skills",
    level: 18,
    type: "fill",
    question: "LoRA 训练的步数计算公式：总训练步数 = 轮数 × 重复次数 × 图片数量，一般建议总步数控制在 ______ 以内。",
    answers: ["3000", "3000步", "≤3000"],
    explanation: "公式：总步数 = 轮数(4) × 重复次数 × 图片数(30)，建议 ≤ 3000。即重复次数 ≈ 3000÷4÷30 ≈ 25 步。步数过多容易过拟合。",
  },
  {
    id: "cu-c05",
    module: "skills",
    level: 18,
    type: "choice",
    question: "LoRA 训练中「正则化处理」的目的是？",
    options: [
      "增加训练步数提升精度",
      "删除所有训练图片中高频共有的强特征词",
      "把所有图片统一成相同文件名格式",
      "测试 LoRA 是否可以正常加载",
    ],
    answerIndex: 1,
    explanation: "正则化 = 删除训练集图片共有的强特征词（如「黑色车顶」「品牌 Logo」），防止模型把触发词和特定外观特征强绑定。目的是让模型学到真正有泛化价值的特征。",
  },
  {
    id: "cu-c06",
    module: "skills",
    level: 20,
    type: "choice",
    question: "LoRA 自动化打标（飞书多维表格 + 火山引擎）共分几个标注维度？",
    options: ["3个", "4个", "5个", "6个"],
    answerIndex: 3,
    explanation: "六维度：主体内容、场景特征、环境光照、画幅视角、画面质量、画面风格。最终将六维度用 AI 整合成一条完整英文 prompt 作为训练标签。",
  },
  {
    id: "cu-ord01",
    module: "skills",
    level: 20,
    type: "order",
    question: "LoRA 训练完整五步流程，按正确顺序排列：",
    steps: [
      "① 收集数据集（15-50张高质量图）",
      "② 统一图片尺寸（768×512 或 512×512）并重命名",
      "③ 自动化打标（六维度 → 整合英文 prompt）",
      "④ 正则化处理（删除高频共有特征词）",
      "⑤ 跑 LoRA 训练工作流",
    ],
    explanation: "收集→尺寸统一→打标→正则化→训练。记忆口诀：「选材→规整→描述→清洗→训练」。",
  },
  {
    id: "cu-tf01",
    module: "skills",
    level: 16,
    type: "truefalse",
    question: "Flux 模型使用的是和 SD 1.5 相同的「Checkpoint 加载器」节点，两者工作流可以互换。",
    correct: false,
    explanation: "错误！Flux 使用专用节点：双 CLIP 加载器（clip_l + t5xxl）、Unity 加载器（替代 Checkpoint）、条件归零节点（替代负向提示词）。不能直接套用 SD 工作流。",
  },
  {
    id: "cu-multi01",
    module: "skills",
    level: 19,
    type: "multi",
    question: "ComfyUI 图生图工作流相比文生图，额外增加了哪些节点？（多选）",
    options: [
      "输入图像节点（上传参考图）",
      "VAE 编码器（把输入图转成潜在空间格式）",
      "Latent 缩放节点（防止超出模型最大分辨率）",
      "双 CLIP 加载器",
    ],
    correctIndexes: [0, 1, 2],
    explanation: "图生图在文生图基础上增加：①加载图像 ②VAE 编码器（与解码器成对）③Latent 缩放（SD 1.5 超出 512 会崩）。双 CLIP 是 Flux 的特有节点，不是图生图的增量。",
  },

  // ============================================================
  // 自动化与数据生产 · PE 调优全链路（技能模块）
  // ============================================================
  {
    id: "pe-c01",
    module: "skills",
    level: 10,
    type: "choice",
    question: "IAA（智能自动化）与 RPA（机器人流程自动化）最本质的区别是？",
    options: [
      "IAA 只能处理文字，RPA 可以处理图像",
      "IAA = RPA 执行底座 + AI/ML/NLP 智能能力，是当前行业主流",
      "RPA 比 IAA 更智能，IAA 是 RPA 的升级版",
      "两者完全相同，只是叫法不同",
    ],
    answerIndex: 1,
    explanation: "IAA = RPA（执行底座）+ AI 智能能力。RPA 只能按规则走固定流程；IAA 加入 AI 后能处理非结构化内容，是当前主流。AI 训练师的价值升级方向：从「做数据」→「设计数据生产方式」。",
  },
  {
    id: "pe-ord01",
    module: "skills",
    level: 14,
    type: "order",
    question: "PE 构建六步 SOP（SOPPE），按正确顺序排列：",
    steps: [
      "① 明确理想态（定验收标准、正反例）",
      "② 测试模型能力边界（分层摸底）",
      "③ 编写初版 Prompt v0.1（先跑通再打磨）",
      "④ 小批量测试（5条×5次，验证稳定性）",
      "⑤ 对照理想态定向调整（归因后一次只改一处）",
      "⑥ 批量测试验收（85%+ 通过率才考虑上线）",
    ],
    explanation: "六步：明确理想态→摸底能力边界→写初版→小批测试→定向调整→批量验收。核心思想：先定验收标准，再写 Prompt，v0.1 目标是「能测」不是「完美」。",
  },
  {
    id: "pe-c02",
    module: "skills",
    level: 12,
    type: "choice",
    question: "PE 小批量测试的标准做法「5条×5次」是指？",
    options: [
      "同一 Prompt 用 5 种不同任务各跑 5 次",
      "每次用 5 条输入，连续跑 5 轮以上，关注输出稳定性而非单次表现",
      "5 个人各测一遍，对比结果",
      "先测 5 次，稳定后再测 5 次",
    ],
    answerIndex: 1,
    explanation: "5条×5次 = 每次约5条输入，连续5次以上，目的是验证「稳定出对」，防止模型「抽卡」（偶然成功）。关注方差而非单次表现，同一输入跑5次对比一致性。",
  },
  {
    id: "pe-c03",
    module: "skills",
    level: 13,
    type: "choice",
    question: "PE 调优时，发现 Prompt 效果不理想，下列哪个做法是正确的？",
    options: [
      "把所有能想到的改动一次性全部修改",
      "归因后再改，一次只动一处，小步快跑",
      "直接换一个全新的 Prompt 重来",
      "增加更多 Few-shot 示例就能解决所有问题",
    ],
    answerIndex: 1,
    explanation: "核心原则：「归因后再改，一次只动一处」。各模块相互关联，大幅改动引入新问题且难定位。金句：「定位问题比修改更重要。」",
  },
  {
    id: "pe-c04",
    module: "skills",
    level: 11,
    type: "choice",
    question: "Few-shot 示例在 PE 中的作用是？",
    options: [
      "让模型记住你的名字和偏好",
      "在 Prompt 里提供 2-3 组「输入→期望输出」配对，让模型推断规则",
      "增加 Prompt 长度，提高 token 消耗",
      "替代系统提示词（System Prompt）的作用",
    ],
    answerIndex: 1,
    explanation: "Few-shot = 在 Prompt 中提供 2-3 对「输入→期望输出」样例，比直接写规则更有效，尤其适合格式要求复杂的任务。模型通过示例推断规则，而不是机械执行文字描述。",
  },
  {
    id: "pe-c05",
    module: "skills",
    level: 15,
    type: "choice",
    question: "温度（Temperature）参数调高时，模型输出会变得？",
    options: ["更准确稳定", "更随机多样但可能不稳定", "更慢更贵", "更短更简洁"],
    answerIndex: 1,
    explanation: "温度越高 → 随机性越强，输出更多样但稳定性下降；温度越低 → 输出越确定、保守。创意类任务高温度，需要精准输出的任务低温度。优先调温度，影响最直观。",
  },
  {
    id: "pe-tf01",
    module: "skills",
    level: 12,
    type: "truefalse",
    question: "PE 批量验收时，如果大多数样本都打了满分，说明评测集质量很高、PE 效果很好。",
    correct: false,
    explanation: "错误！大多数满分 = 题目太简单了，没有区分度，评测等于白做。评测集的难度要设计成简单、中等、困难三个梯度，目标是区分出不同模型的能力边界，不是让所有模型都考满分。",
  },
  {
    id: "pe-c06",
    module: "skills",
    level: 16,
    type: "choice",
    question: "PE 调优时，模型最难做到的三类任务包括？",
    options: [
      "简单问答、文本翻译、格式转换",
      "安全性边界判断、高精度美学感知、情感化分析",
      "数学计算、代码生成、文本摘要",
      "关键词提取、分类打标、是非判断",
    ],
    answerIndex: 1,
    explanation: "模型能力天花板：①安全边界判断（灰色地带难定义）②高精度美学感知（主观性强）③情感化分析（文化语境复杂）。摸底测试时重点关注这三类。",
  },
  {
    id: "pe-c07",
    module: "skills",
    level: 17,
    type: "choice",
    question: "PE 构建中，「自我反思」机制的正确操作流程是？",
    options: [
      "让模型先输出结果，然后让模型自己检查是否符合约束，有问题则修正",
      "人工反复检查 Prompt，找出逻辑漏洞",
      "让两个不同模型互相批改对方的输出",
      "在 Prompt 中加入「请你认真思考」等提示语",
    ],
    answerIndex: 0,
    explanation: "自我反思三步：①模型输出结果 ②模型回顾输出逐条对照约束（对了也总结）③有问题则修正。类比：数学题做完再检查一遍。可有效减少格式错和逻辑偏问题。",
  },
  {
    id: "pe-multi01",
    module: "skills",
    level: 14,
    type: "multi",
    question: "PE 批量测试验收（ACCEPT）环节的三种验收方法包括哪些？（多选）",
    options: ["人工逐条打分", "模型自动评分（LLM as Judge）", "标准答案对比", "A/B 测试对比上一个版本"],
    correctIndexes: [0, 1, 2],
    explanation: "三种验收方法：①人工打分 ②模型自评（LLM as Judge）③标准答案对比。85%+ 通过率可考虑上线；某类集中出错时，单独剔该类走人工审核，不影响整体上线。",
  },

  // ============================================================
  // 竞品评测 · 课堂笔记（面试模块）
  // ============================================================
  {
    id: "cp-c01",
    module: "interview",
    level: 8,
    type: "choice",
    question: "AI 竞品分析的四大维度是？",
    options: [
      "价格、颜值、速度、口碑",
      "市场定位、模型技术、产品功能、用户体验",
      "融资金额、团队规模、专利数量、媒体报道",
      "MAU、DAU、留存率、转化率",
    ],
    answerIndex: 1,
    explanation: "竞品分析四维度：①市场定位（卡什么位置）②模型技术（底层能力）③产品功能（有哪些功能）④用户体验（用起来舒不舒服）。面试必背！",
  },
  {
    id: "cp-c02",
    module: "interview",
    level: 10,
    type: "choice",
    question: "OpenAI 提出的「通往 AGI 五阶段」，当前主流 AI 处于哪个阶段？",
    options: ["L1 会话（Chatbots）", "L2 推理（Reasoners）", "L3 智能体（Agents）", "L4 创新（Innovators）"],
    answerIndex: 2,
    explanation: "AGI 五阶段：L1 聊天 → L2 推理 → L3 Agent → L4 创新 → L5 组织。当前阶段是 L3（Agent），L4 有部分突破，L5 是未来目标。面试被问到直接答 L3。",
  },
  {
    id: "cp-c03",
    module: "interview",
    level: 9,
    type: "choice",
    question: "竞品中「直接竞品」和「间接竞品」的区别是？",
    options: [
      "直接竞品贵，间接竞品便宜",
      "直接竞品功能相似且争夺同一批用户；间接竞品解决同一痛点但方式不同",
      "直接竞品是国内产品，间接竞品是海外产品",
      "直接竞品已上线，间接竞品还在开发中",
    ],
    answerIndex: 1,
    explanation: "直接竞品：功能几乎一样、用户高度重叠（如豆包 vs 千问）。间接竞品：解决同一用户痛点但路径不同（如地铁/共享单车/滴滴，都是出行但方式不同）。还有潜在竞品：现在不构成威胁但未来可能抢市场。",
  },
  {
    id: "cp-c04",
    module: "interview",
    level: 11,
    type: "choice",
    question: "产品功能分析中，「隐性功能」是指？",
    options: [
      "界面上能看到但点不了的功能",
      "界面上看不见但真实存在、需要主动测试才能发现的功能",
      "付费会员才能使用的功能",
      "仅限内部测试的功能",
    ],
    answerIndex: 1,
    explanation: "隐性功能 = 界面不标注但真实存在，如 Claude 生成可交互分析图、某模型输出可直接渲染的网页代码。挖掘技巧：直接往里输东西，看它输出什么格式，不能只看界面写了什么。",
  },
  {
    id: "cp-c05",
    module: "interview",
    level: 12,
    type: "choice",
    question: "竞品分析报告最核心的写作原则是？",
    options: [
      "字数越多越专业，体现工作量",
      "结论前置！先告诉老板谁最强、有什么差距，再展示数据",
      "先展示大量数据，最后才写结论",
      "每个维度平均分配篇幅，保持客观",
    ],
    answerIndex: 1,
    explanation: "结论前置是核心！老板没时间看过程，先告诉他：谁最强/哪里有差距/我们要注意什么。报告三大禁忌：①只说结论不给数据 ②全程没有截图 ③评测集里没有 response 链接（别人无法复现）。",
  },
  {
    id: "cp-tf01",
    module: "interview",
    level: 8,
    type: "truefalse",
    question: "做竞品分析时，模型技术方面的信息（架构、参数量等）主要通过「产品体验」获取。",
    correct: false,
    explanation: "错误！模型技术信息靠「查公开资料」：arxiv.org（AI 技术论文）、GitHub/HuggingFace（开源信息）。产品体验解决的是「产品功能」和「用户体验」两个维度，技术细节靠体验是看不出来的。",
  },
  {
    id: "cp-c06",
    module: "interview",
    level: 14,
    type: "choice",
    question: "构建模型评测集时，发现 80% 的数据都打了满分，应该怎么处理？",
    options: [
      "说明模型很强，直接输出报告",
      "说明题目太简单没有区分度，需要增加中等难度和困难题目",
      "删除满分数据，只保留不满分的",
      "换评测员重新打分",
    ],
    answerIndex: 1,
    explanation: "满分过多 = 评测集难度不够，没有区分度。评测集的难度要设计成简单/中等/困难三个梯度，目标是找到不同模型的能力边界，不是让所有模型考满分。这是课堂「血的教训」案例。",
  },
  {
    id: "cp-multi01",
    module: "interview",
    level: 10,
    type: "multi",
    question: "竞品分析数据收集的三种主要方式是？（多选）",
    options: ["查公开资料（arxiv/行业报告）", "产品体验（功能测试）", "用户调研（访谈/问卷/评论区）", "向竞争对手直接索要数据"],
    correctIndexes: [0, 1, 2],
    explanation: "三种方式：①公开资料（解决市场定位+模型技术）②产品体验（解决产品功能+用户体验）③用户调研（挖真实痛点和迭代方向）。每种方式解决不同维度，组合使用才完整。",
  },
  {
    id: "cp-c07",
    module: "interview",
    level: 13,
    type: "choice",
    question: "模型选型时，「成本」维度考虑的核心是？",
    options: [
      "价格越低越好，省钱是第一位",
      "质量越高越好，效果最重要",
      "在业务场景下找性价比最高的，不是越便宜或越贵越好",
      "选知名度最高的大厂模型",
    ],
    answerIndex: 2,
    explanation: "模型选型核心：性价比最优，不是最便宜也不是最强。选型五维度：模态（文/图/视频）、能力（推理/代码等）、形态（API/开源/私有化）、成本（token计费）、时延（首字延迟/上下文窗口）。",
  },
  {
    id: "cp-ord01",
    module: "interview",
    level: 12,
    type: "order",
    question: "竞品分析的完整流程，按正确顺序排列：",
    steps: [
      "① 明确目标（搞清楚给谁看、他们关注什么）",
      "② 确定竞品（相似功能+同一目标用户+可互相替代）",
      "③ 确定分析维度（根据目标从四大模块选）",
      "④ 数据收集（公开资料+产品体验+用户调研）",
      "⑤ 分析整理，输出报告（结论前置）",
    ],
    explanation: "竞品分析五步：明确目标→确定竞品→确定维度→收集数据→输出报告。第一步「明确目标」最关键——给老板/产品/研发/运营看，关注点完全不同。",
  },
  {
    id: "cp-tf02",
    module: "interview",
    level: 9,
    type: "truefalse",
    question: "竞品分析报告中，「SWOT 分析」模块应该放在报告最前面作为开篇。",
    correct: false,
    explanation: "错误！报告结构是：背景→市场概览→竞品信息→核心评测结果（结论前置）→详细分析→数据展示→SWOT分析→结论与建议。SWOT 在后段，最前面是结论（谁强谁弱/有哪些差距）。",
  },
  {
    id: "cp-c08",
    module: "interview",
    level: 15,
    type: "choice",
    question: "对不同受众输出竞品分析报告时，下列说法正确的是？",
    options: [
      "报告应该统一格式，对所有人展示完全相同的内容",
      "老板看全局格局，研发关心技术差距，运营关心留存收入",
      "只需要给老板看，其他人不需要了解竞品情况",
      "报告越详细越好，所有信息都应该包含",
    ],
    answerIndex: 1,
    explanation: "不同受众关注点不同：老板 → 全面市场格局；产品团队 → 功能差距；研发团队 → 技术实现；运营团队 → 留存/收入/用户体验。明确受众是做竞品分析的第一步。",
  },
];
